LAST_NAMES = {
    'Phan', 'Nguyễn', 'Lê', 'Trần',
    'Tống', 'Lại', 'Đỗ', 'Đặng',
    'Ngô', 'Nghiêm', 'Lương', 'Quách',
    'Vũ', 'Đinh', 'Phạm', 'Huỳnh',
    'Hoàng', 'Bùi', 'Võ', 'Hồ', 'Dương',
    'Đoàn', 'Trịnh', 'Trương', 'Phùng',
    'Tạ', 'Triệu', 'Chu'
}

MIDDLE_NAMES = {
    'Văn', 'Thị', 'Đình', 'Ngọc',
    'Thành', 'Như', 'Chí', 'Đức',
    'Thanh', 'Thu', 'Xuân', 'Cẩm',
    'Hồng', 'Hoàng', 'Cao', 'Trung',
    'Anh', 'Kỳ', 'Nam', 'Tuấn',
    'Tường', 'Phương', 'Huyền',
    'Huy', 'Hồng', 'Lan',
    'Lâm', 'Mạnh', 'Vân',
    'Hương', 'Minh', 'Việt',
    'Quang', 'Diệu', 'Quỳnh',
}

FIRST_NAMES = {
    'Văn', 'Đình', 'Ngọc', 'Huyền',
    'Thành', 'Như', 'Chí', 'Đức',
    'Thanh', 'Thu', 'Xuân', 'Tú',
    'Hồng', 'Hoàng', 'Đại', 'Nam',
    'Anh', 'Hạnh', 'Nhân', 'Kỳ',
    'Vinh', 'Linh', 'Chi', 'Ly',
    'Thảo', 'Phương', 'Trinh', 'Lân',
    'Huy', 'Hồng', 'Nga', 'Thắng',
    'Cường', 'Dũng', 'Vy', 'Lan',
    'Lâm', 'Hiếu', 'Mạnh', 'Vân',
    'Hương', 'Minh', 'Đạt', 'Thịnh',
    'Vương', 'Long', 'Quang', 'Diệu',
    'Bảo', 'Trí', 'Trung', 'Quân',
    'Quỳnh', 'Yến', 'An', 'My',
    'Lợi', 'Việt', 'Tuấn'
}

MAJORS = [
    {'name': 'CNTT-TT',
     'group': 'A'},
    {'name': 'Tự động hóa',
     'group': 'A'},
    {'name': 'Điện tử viễn thông',
     'group': 'A'},
    {'name': 'Cơ điện tử',
     'group': 'A'},
    {'name': 'Cơ khí',
     'group': 'A'},
    {'name': 'Kỹ thuật hóa học',
     'group': 'A'},
    {'name': 'Quản trị kinh doanh',
     'group': 'A'},
    {'name': 'Quản trị du lịch',
     'group': 'D'},
    {'name': 'Tiếng Anh',
     'group': 'D'},
    {'name': 'Tiếng Pháp',
     'group': 'D'},
    {'name': 'Tiếng Đức',
     'group': 'D'},
    {'name': 'Tiếng Nhật',
     'group': 'D'},
    {'name': 'Marketing',
     'group': 'D'},
    {'name': 'Kế toán',
     'group': 'A'},
    {'name': 'Kiểm toán',
     'group': 'A'},
    {'name': 'Tài chính - Ngân hàng',
     'group': 'A'},
    {'name': 'Công nghệ sinh học',
     'group': 'A'},
]

SCHOOLS = [
    {'name': 'Đại học Bách Khoa Hà Nội',
     'majors': [
        {'name': 'CNTT-TT',
         'cutoff': 400},
        {'name': 'Tự động hóa',
         'cutoff': 300},
        {'name': 'Điện tử viễn thông',
         'cutoff': 350},
        {'name': 'Cơ khí',
         'cutoff': 200},
        {'name': 'Kỹ thuật hóa học',
         'cutoff': 150},
        {'name': 'Cơ điện tử',
         'cutoff': 350},
        {'name': 'Tiếng Anh',
         'cutoff': 200},
        {'name': 'Công nghệ sinh học',
         'cutoff': 220},
     ]},
    {'name': 'Đại học Kinh tế Quốc dân',
     'majors': [
         {'name': 'Quản trị kinh doanh',
          'cutoff': 420},
         {'name': 'Quản trị du lịch',
          'cutoff': 210},
         {'name': 'Marketing',
          'cutoff': 300},
         {'name': 'Kế toán',
          'cutoff': 420},
         {'name': 'Kiểm toán',
          'cutoff': 420},
         {'name': 'Tài chính - Ngân hàng',
          'cutoff': 420},
         {'name': 'Tiếng Anh',
          'cutoff': 420},
     ]},
    {'name': 'Đại học Xây dựng',
     'majors': [
        {'name': 'CNTT-TT',
         'cutoff': 200},
        {'name': 'Tự động hóa',
         'cutoff': 300},
        {'name': 'Điện tử viễn thông',
         'cutoff': 350},
        {'name': 'Cơ khí',
         'cutoff': 200},
        {'name': 'Quản trị kinh doanh',
         'cutoff': 150},
        {'name': 'Kế toán',
         'cutoff': 350},
        {'name': 'Tiếng Anh',
         'cutoff': 200},
     ]},
    {'name': 'Đại học Ngoại thương',
     'majors': [
         {'name': 'Quản trị kinh doanh',
          'cutoff': 500},
         {'name': 'Marketing',
          'cutoff': 320},
         {'name': 'Kế toán',
          'cutoff': 270},
         {'name': 'Kiểm toán',
          'cutoff': 200},
         {'name': 'Tiếng Nhật',
          'cutoff': 300},
         {'name': 'Tiếng Pháp',
          'cutoff': 150},
         {'name': 'Tiếng Đức',
          'cutoff': 180},
         {'name': 'Tài chính - Ngân hàng',
          'cutoff': 310},
         {'name': 'Tiếng Anh',
          'cutoff': 300},
     ]},
    {'name': 'Đại học Thương mại',
     'majors': [
         {'name': 'Quản trị kinh doanh',
          'cutoff': 500},
         {'name': 'Marketing',
          'cutoff': 320},
         {'name': 'Kế toán',
          'cutoff': 270},
         {'name': 'Kiểm toán',
          'cutoff': 200},
         {'name': 'Tiếng Nhật',
          'cutoff': 300},
         {'name': 'Tiếng Pháp',
          'cutoff': 150},
         {'name': 'Tiếng Đức',
          'cutoff': 180},
         {'name': 'Tài chính - Ngân hàng',
          'cutoff': 310},
         {'name': 'Tiếng Anh',
          'cutoff': 300},
     ]},
    {'name': 'Đại học Kinh tế Kỹ thuật Công nghiệp',
     'majors': [
         {'name': 'Quản trị kinh doanh',
          'cutoff': 300},
         {'name': 'Marketing',
          'cutoff': 250},
         {'name': 'Kế toán',
          'cutoff': 210},
         {'name': 'Kiểm toán',
          'cutoff': 150},
         {'name': 'Tài chính - Ngân hàng',
          'cutoff': 220},
         {'name': 'Tiếng Anh',
          'cutoff': 130},
     ]},
    {'name': 'Đại học Kinh doanh Công nghệ',
     'majors': [
         {'name': 'Quản trị kinh doanh',
          'cutoff': 300},
         {'name': 'Marketing',
          'cutoff': 250},
         {'name': 'Kế toán',
          'cutoff': 210},
         {'name': 'Kiểm toán',
          'cutoff': 150},
         {'name': 'Tài chính - Ngân hàng',
          'cutoff': 220},
         {'name': 'Tiếng Anh',
          'cutoff': 130},
     ]},
    {'name': 'Đại học Hà Nội',
     'majors': [
         {'name': 'Marketing',
          'cutoff': 200},
         {'name': 'Kế toán',
          'cutoff': 120},
         {'name': 'CNTT-TT',
          'cutoff': 170},
         {'name': 'Quản trị du lịch',
          'cutoff': 280},
         {'name': 'Tiếng Anh',
          'cutoff': 300},
         {'name': 'Tiếng Nhật',
          'cutoff': 320},
         {'name': 'Tiếng Pháp',
          'cutoff': 250},
         {'name': 'Tiếng Đức',
          'cutoff': 220},
     ]},
    {'name': 'Viện Đại học Mở',
     'majors': [
         {'name': 'CNTT-TT',
          'cutoff': 200},
         {'name': 'Điện tử viễn thông',
          'cutoff': 120},
         {'name': 'Quản trị kinh doanh',
          'cutoff': 180},
         {'name': 'Quản trị du lịch',
          'cutoff': 190},
         {'name': 'Marketing',
          'cutoff': 140},
         {'name': 'Kế toán',
          'cutoff': 200},
         {'name': 'Kiểm toán',
          'cutoff': 230},
         {'name': 'Tài chính - Ngân hàng',
          'cutoff': 200},
         {'name': 'Tiếng Anh',
          'cutoff': 300},

     ]},
    {'name': 'Đại học Ngoại ngữ',
     'majors': [
         {'name': 'Tiếng Anh',
          'cutoff': 300},
         {'name': 'Tiếng Nhật',
          'cutoff': 320},
         {'name': 'Tiếng Pháp',
          'cutoff': 250},
         {'name': 'Tiếng Đức',
          'cutoff': 220},

     ]},
    {'name': 'Đại học Khoa học Xã hội và Nhân văn',
     'majors': [
         {'name': 'Tiếng Anh',
          'cutoff': 300},
         {'name': 'Tiếng Nhật',
          'cutoff': 320},
         {'name': 'Tiếng Pháp',
          'cutoff': 200},
         {'name': 'Tiếng Đức',
          'cutoff': 220},
     ]},
    {'name': 'Đại học Công nghệ',
     'majors': [
         {'name': 'CNTT-TT',
          'cutoff': 300},
         {'name': 'Tự động hóa',
          'cutoff': 210},
         {'name': 'Điện tử viễn thông',
          'cutoff': 300},
         {'name': 'Cơ khí',
          'cutoff': 200},
         {'name': 'Kỹ thuật hóa học',
          'cutoff': 150},
         {'name': 'Cơ điện tử',
          'cutoff': 350},
         {'name': 'Công nghệ sinh học',
          'cutoff': 250},
     ]},
    {'name': 'Đại học Thăng Long',
     'majors': [
         {'name': 'CNTT-TT',
          'cutoff': 200},
         {'name': 'Điện tử viễn thông',
          'cutoff': 120},
         {'name': 'Quản trị kinh doanh',
          'cutoff': 180},
         {'name': 'Quản trị du lịch',
          'cutoff': 190},
         {'name': 'Marketing',
          'cutoff': 140},
         {'name': 'Kế toán',
          'cutoff': 200},
         {'name': 'Kiểm toán',
          'cutoff': 230},
         {'name': 'Tài chính - Ngân hàng',
          'cutoff': 200},
         {'name': 'Tiếng Anh',
          'cutoff': 300},

     ]},
    {'name': 'Học viện Kĩ thuật Quân sự',
     'majors': [
         {'name': 'CNTT-TT',
          'cutoff': 280},
         {'name': 'Tự động hóa',
          'cutoff': 190},
         {'name': 'Điện tử viễn thông',
          'cutoff': 300},
         {'name': 'Cơ khí',
          'cutoff': 200},
         {'name': 'Kỹ thuật hóa học',
          'cutoff': 150},
         {'name': 'Cơ điện tử',
          'cutoff': 380},
     ]},
]
